### ISSUE TITLE
task: get vlogging

### ISSUE THREAD

**Issue by trulysinclair** [trulysinclair/trulysinclair-server#9]
Stop procrastinating and get out there. Please do what you need to, but get it done. 

## Checklist

- [x] Camera
- [ ] Microphone
- [x] Editing Software (Clipchamp, Remotion later?)
- [x] Recording Software (OBS)
- [x] Something to do (this server as a series?)

### Project Management

Talk about setting up a basic flow from idea, to issue, to branch, to pr, and how it moves through the project board. What automation is in place?

#### Tasks

The grunt work.

#### Board(s)

Kanbans and tables.

#### Milestones

Reasonable goals, either versions or features. It's the scale of the problem. Maybe.

#### Priority

Is it really that important?

### Timeline

Where ADHD goes to die.

#### Rough Projections

How long will it take to implement a simple category route? Does it need multiple pages or complex components? How far does the diff go in your head?

### Design (for lack thereof)

Focus on the functionality before you get lost in form.
